In [2]:
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

import os

import IPython.display as ipd

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import librosa
import librosa.display
import ast


plt.rcParams['figure.figsize'] = (17, 5)

###Â Creating a CSV file for all features of audio

In [19]:

header = 'filename chroma_cqt chroma_cens chroma_stft spectral_centroid spectral_bandwidth spectral_contrast rolloff zero_crossing_rate tonnetz'
for i in range(1, 21):
    header += f' mfcc{i}'
header = header.split()

In [7]:
from pathlib import Path

In [22]:


file = open('data.csv', 'w', newline='')
with file:
    writer = csv.writer(file)
    writer.writerow(header)
data_dir = 'data/music/'
for filename in os.listdir(data_dir):
    full_path = f'{data_dir}{filename}'
    trackname = filename.split(".")
# for filename in os.listdir(f'./MIR/genres/{g}'):
#     songname = f'./MIR/genres/{g}/{filename}'
    y, sr = librosa.load(full_path, mono=True, duration=30)
    chroma_cqt = librosa.feature.chroma_cqt(y=y,sr=sr)
    chroma_cens = librosa.feature.chroma_cens(y=y,sr=sr)
    chroma_stft = librosa.feature.chroma_stft(y=y, sr=sr)
    spec_cent = librosa.feature.spectral_centroid(y=y, sr=sr)
    spec_bw = librosa.feature.spectral_bandwidth(y=y, sr=sr)
    spec_con = librosa.feature.spectral_contrast(y=y,sr=sr)
    rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr)
    zcr = librosa.feature.zero_crossing_rate(y)
    tonnetz = librosa.feature.tonnetz(y=y, sr=sr)
    mfcc = librosa.feature.mfcc(y=y, sr=sr)
    to_append = f'{trackname[0]} {np.mean(chroma_cqt)} {np.mean(chroma_cens)} {np.mean(chroma_stft)} {np.mean(spec_cent)} {np.mean(spec_bw)} {np.mean(spec_con)} {np.mean(rolloff)} {np.mean(zcr)} {np.mean(tonnetz)}'    
    for e in mfcc:
        to_append += f' {np.mean(e)}'
    file = open('data.csv', 'a', newline='')
    with file:
        writer = csv.writer(file)
        writer.writerow(to_append.split())

# Creatin new CSV for root mean square energy

In [4]:
header = 'filename rmse'

In [8]:

file = open('rmse.csv', 'w', newline='')
with file:
    writer = csv.writer(file)
    writer.writerow(header)
data_dir = '../data/music/'
for filename in os.listdir(data_dir):
    full_path = f'{data_dir}{filename}'
    trackname = filename.split(".")
    y, sr = librosa.load(full_path, mono=True, duration=30)
    rmse = librosa.feature.rms(y)
    to_append = f'{trackname[0]} {np.mean(rmse)}'
    file = open('rmse.csv', 'a', newline='')
    with file:
        writer = csv.writer(file)
        writer.writerow(to_append.split())

In [3]:
df2 = pd.read_csv('rmse.csv')

In [4]:
df2.rename({'f':'track_id','i':'rmse'},axis=1,inplace=True)

In [5]:
df2 = df2[['track_id','rmse']]

In [6]:
df2.head()

   track_id      rmse
0    126014  0.074824
1     54496  0.030249
2     65893  0.206977
3     71158  0.241167
4     57821  0.270437

In [7]:
df = pd.read_csv('../data.csv')

In [8]:
df.head()

,filename,chroma_cqt,chroma_cens,chroma_stft,spectral_centroid,spectral_bandwidth,spectral_contrast,rolloff,zero_crossing_rate,tonnetz,...,mfcc11,mfcc12,mfcc13,mfcc14,mfcc15,mfcc16,mfcc17,mfcc18,mfcc19,mfcc20
0,126014,0.267008,0.171130,0.237383,699.229710,785.999971,25.676751,1183.751175,0.041712,0.092841,...,-27.326481,-20.607473,-12.659972,-13.275584,-12.988043,-15.687397,-12.339302,2.211766,2.147864,-5.011512
1,54496,0.274600,0.207362,0.277710,1833.074733,2091.124342,25.274995,3818.560243,0.093890,0.044640,...,-5.424025,6.843907,-6.247772,3.441898,-0.244973,4.090439,-1.278771,9.071951,-0.169724,0.161876
2,65893,0.458305,0.253559,0.412075,2767.487106,2741.112704,20.450162,5889.689386,0.111506,0.013648,...,-8.586940,6.649025,-2.908488,3.085722,-3.682684,2.957125,-2.243021,1.578797,-4.537785,1.052801
3,71158,0.531325,0.258276,0.424391,1444.225428,2060.084462,19.861984,3089.631317,0.046734,0.000029,...,5.303405,-0.030636,-1.089045,2.822888,-2.630777,1.943587,-7.131413,1.516889,-0.094114,-0.776687
4,57821,0.412456,0.239312,0.335196,2253.305912,2412.719760,22.327731,4858.028957,0.099870,0.024816,...,-8.056653,-5.495337,-8.891809,-2.783748,-6.777088,-3.736772,-11.871335,-0.826213,-2.934075,6.011378

In [9]:
df.rename({'filename':'track_id'},axis=1,inplace=True)

In [10]:
df.head()

,track_id,chroma_cqt,chroma_cens,chroma_stft,spectral_centroid,spectral_bandwidth,spectral_contrast,rolloff,zero_crossing_rate,tonnetz,...,mfcc11,mfcc12,mfcc13,mfcc14,mfcc15,mfcc16,mfcc17,mfcc18,mfcc19,mfcc20
0,126014,0.267008,0.171130,0.237383,699.229710,785.999971,25.676751,1183.751175,0.041712,0.092841,...,-27.326481,-20.607473,-12.659972,-13.275584,-12.988043,-15.687397,-12.339302,2.211766,2.147864,-5.011512
1,54496,0.274600,0.207362,0.277710,1833.074733,2091.124342,25.274995,3818.560243,0.093890,0.044640,...,-5.424025,6.843907,-6.247772,3.441898,-0.244973,4.090439,-1.278771,9.071951,-0.169724,0.161876
2,65893,0.458305,0.253559,0.412075,2767.487106,2741.112704,20.450162,5889.689386,0.111506,0.013648,...,-8.586940,6.649025,-2.908488,3.085722,-3.682684,2.957125,-2.243021,1.578797,-4.537785,1.052801
3,71158,0.531325,0.258276,0.424391,1444.225428,2060.084462,19.861984,3089.631317,0.046734,0.000029,...,5.303405,-0.030636,-1.089045,2.822888,-2.630777,1.943587,-7.131413,1.516889,-0.094114,-0.776687
4,57821,0.412456,0.239312,0.335196,2253.305912,2412.719760,22.327731,4858.028957,0.099870,0.024816,...,-8.056653,-5.495337,-8.891809,-2.783748,-6.777088,-3.736772,-11.871335,-0.826213,-2.934075,6.011378

In [11]:
df = pd.merge(df,df2,on='track_id')

In [12]:
df.head()

,track_id,chroma_cqt,chroma_cens,chroma_stft,spectral_centroid,spectral_bandwidth,spectral_contrast,rolloff,zero_crossing_rate,tonnetz,...,mfcc12,mfcc13,mfcc14,mfcc15,mfcc16,mfcc17,mfcc18,mfcc19,mfcc20,rmse
0,126014,0.267008,0.171130,0.237383,699.229710,785.999971,25.676751,1183.751175,0.041712,0.092841,...,-20.607473,-12.659972,-13.275584,-12.988043,-15.687397,-12.339302,2.211766,2.147864,-5.011512,0.074824
1,54496,0.274600,0.207362,0.277710,1833.074733,2091.124342,25.274995,3818.560243,0.093890,0.044640,...,6.843907,-6.247772,3.441898,-0.244973,4.090439,-1.278771,9.071951,-0.169724,0.161876,0.030249
2,65893,0.458305,0.253559,0.412075,2767.487106,2741.112704,20.450162,5889.689386,0.111506,0.013648,...,6.649025,-2.908488,3.085722,-3.682684,2.957125,-2.243021,1.578797,-4.537785,1.052801,0.206977
3,71158,0.531325,0.258276,0.424391,1444.225428,2060.084462,19.861984,3089.631317,0.046734,0.000029,...,-0.030636,-1.089045,2.822888,-2.630777,1.943587,-7.131413,1.516889,-0.094114,-0.776687,0.241167
4,57821,0.412456,0.239312,0.335196,2253.305912,2412.719760,22.327731,4858.028957,0.099870,0.024816,...,-5.495337,-8.891809,-2.783748,-6.777088,-3.736772,-11.871335,-0.826213,-2.934075,6.011378,0.270437

In [13]:
genres = pd.read_csv('../data/fma_metadata/genrelist.csv')

In [14]:
genres

     Unnamed: 0    genre testtrainval
0           NaN      NaN          NaN
1      track_id      NaN          NaN
2             2  Hip-Hop     training
3             5  Hip-Hop     training
4            10      Pop     training
...         ...      ...          ...
7997     154308  Hip-Hop         test
7998     154309  Hip-Hop         test
7999     154413      Pop     training
8000     154414      Pop     training
8001     155066  Hip-Hop     training

[8002 rows x 3 columns]

In [15]:
genres.drop([0,1],axis=0,inplace=True)

In [16]:
genres.head()

  Unnamed: 0    genre testtrainval
2          2  Hip-Hop     training
3          5  Hip-Hop     training
4         10      Pop     training
5        140     Folk     training
6        141     Folk     training

In [17]:
genres.rename({'Unnamed: 0':'track_id'},axis=1,inplace=True)

In [18]:
genres['track_id'] = genres['track_id'].astype('int64')

In [19]:
data=pd.merge(df,genres,on='track_id')

In [20]:
data['genre']

0        Instrumental
1        Experimental
2                Folk
3             Hip-Hop
4             Hip-Hop
            ...
7992    International
7993     Experimental
7994              Pop
7995     Experimental
7996     Instrumental
Name: genre, Length: 7997, dtype: object

In [21]:
data.set_index('track_id',inplace=True)

In [22]:
data.head()

,chroma_cqt,chroma_cens,chroma_stft,spectral_centroid,spectral_bandwidth,spectral_contrast,rolloff,zero_crossing_rate,tonnetz,mfcc1,...,mfcc14,mfcc15,mfcc16,mfcc17,mfcc18,mfcc19,mfcc20,rmse,genre,testtrainval
track_id,,,,,,,,,,,,,,,,,,,,,
126014,0.267008,0.171130,0.237383,699.229710,785.999971,25.676751,1183.751175,0.041712,0.092841,-352.161438,...,-13.275584,-12.988043,-15.687397,-12.339302,2.211766,2.147864,-5.011512,0.074824,Instrumental,training
54496,0.274600,0.207362,0.277710,1833.074733,2091.124342,25.274995,3818.560243,0.093890,0.044640,-290.169464,...,3.441898,-0.244973,4.090439,-1.278771,9.071951,-0.169724,0.161876,0.030249,Experimental,training
65893,0.458305,0.253559,0.412075,2767.487106,2741.112704,20.450162,5889.689386,0.111506,0.013648,-80.027184,...,3.085722,-3.682684,2.957125,-2.243021,1.578797,-4.537785,1.052801,0.206977,Folk,training
71158,0.531325,0.258276,0.424391,1444.225428,2060.084462,19.861984,3089.631317,0.046734,0.000029,-123.564980,...,2.822888,-2.630777,1.943587,-7.131413,1.516889,-0.094114,-0.776687,0.241167,Hip-Hop,training
57821,0.412456,0.239312,0.335196,2253.305912,2412.719760,22.327731,4858.028957,0.099870,0.024816,-71.340874,...,-2.783748,-6.777088,-3.736772,-11.871335,-0.826213,-2.934075,6.011378,0.270437,Hip-Hop,training

In [23]:
data.to_csv('../data/Final-csvs/features.csv')